### ISSUE TITLE
Adding Robot cause problem

### ISSUE THREAD

**Issue by Nash-dc** [Multiverse-Framework/Multiverse#11]
HI Mr.Hoang,
I already integrate Multiverse in my thesis, thank you again!
I found a very weird thing when I run demo `multi_mujoco_sim_force`
I run the command `roslaunch mujoco_sim multi_mujoco_sim_force.launch` then everything looks perfect.When I move the cube in runtime,the cube in MuJoCo is also moved in the meantime
[Screencast from 17.08.2023 15:56:39.webm](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/8a030213-1ca5-49be-a296-292409be94c1)
But after I add a robot(DualPanda for example) in scene and MultiverseActor.Then I move the cube in Unreal, however the cube in MuJoCo keep still,and the sphere didn't fall.
[Screencast from 17.08.2023 16:28:52.webm](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/401ae725-ef5f-4549-8219-367b24d5ee46)

All these weird things happen after Adding the Robot in MultiverseActor .I tried to find a reason in source code.But after go through the file [mj_multiverse_client.cpp](https://github.com/Multiverse-Framework/Multiverse-MuJoCo-Connector/blob/a2eb0759771150daa3f508fd5ffedf7657543204/mujoco_sim/src/mujoco_sim/mj_multiverse_client.cpp),I stll got no clue.
It would be appreciated that you can give me some brief guidance!

**Comment by HoangGiang93** [comment]
I'm refactoring my framework structure. It's almost done, tomorrow I will notify if I checked everything ok

**Comment by Nash-dc** [comment]
thanks for your work!
hope everything goes well

**Comment by HoangGiang93** [comment]
I updated my code in [Multiverse](https://github.com/Multiverse-Framework/Multiverse) and [Multiverse-UnrealEngine-Demos](https://github.com/Multiverse-Framework/Multiverse-UnrealEngine-Demos). You can follow my [video](https://seafile.zfn.uni-bremen.de/f/467480f10e454a7892d5/) to try it out.
About your question, if you want to add a new robot in Unreal and controlled by MuJoCo, try the second one. Look into the [launch](https://github.com/Multiverse-Framework/Multiverse-Robots/tree/main/universal_robots/ur_mujoco/launch) file I created to understand how to configure a new one. Sorry currently I'm busy to write a proper tutorial, it will happen in the next few weeks.

**Comment by Nash-dc** [comment]
Hi Mr.Hoang,
Thanks for your reply and instructions.
When I rebuild Multiverse,some problem occurs,after I run `./build_multiverse.sh`
```
[90%] Building multiverse_parser package
/bin/sh: 1: /home/dacheng/Documents/Multiverse/multiverse/bin/python3.10: not found
make[2]: *** [modules/multiverse_parser/CMakeFiles/multiverse_parser_build.dir/build.make:71: modules/multiverse_parser/CMakeFiles/multiverse_parser_build] Error 127
make[2]: Leaving directory '/home/dacheng/Documents/Multiverse/multiverse/build/multiverse'
make[1]: *** [CMakeFiles/Makefile2:292: modules/multiverse_parser/CMakeFiles/multiverse_parser_build.dir/all] Error 2
make[1]: Leaving directory '/home/dacheng/Documents/Multiverse/multiverse/build/multiverse'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/dacheng/Documents/Multiverse/multiverse/build/multiverse'
-- Install configuration: ""
-- Up-to-date: /home/dacheng/Documents/Multiverse/multiverse/bin/multiverse_server
-- Up-to-date: /home/dacheng/Documents/Multiverse/multiverse/lib/libstdc++/libmultiverse_client.a
-- Up-to-date: /home/dacheng/Documents/Multiverse/multiverse/lib/libstdc++/libmultiverse_client_json.so
-- Up-to-date: /home/dacheng/Documents/Multiverse/multiverse/lib/libstdc++/python/multiverse_client_pybind.cpython-38-x86_64-linux-gnu.so
```
I checked the python3.10,and I found it is broken
![Screenshot from 2023-08-20 10-18-25](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/1467c5e2-6d91-4e8e-9541-5e4b7bf6f7c3)
It seems there are some problems in blender.So I checked blender file
![Screenshot from 2023-08-20 10-21-22](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/f4d236b5-bb58-405c-b2b6-c09fe19f62bb)
there is no bin file

**But Multiverserver can run properly,and the connection to Unreal is established, so I just leave it.**

Back to my question, I want to add a new robot in Unreal and controlled by MuJoCo, and add a cube in MuJoCo and controlled by Unreal, so I set the MultiverseActor like this:
![Screenshot from 2023-08-20 10-26-25](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/a7680b8c-7e35-4936-bc60-d0fedd68ed51)

and I modify the [empty.xml](https://github.com/Multiverse-Framework/Multiverse-MuJoCo-Connector/blob/main/mujoco_sim/model/world/empty.xml) and [ur5e.yam](https://github.com/Multiverse-Framework/Multiverse-Robots/blob/main/universal_robots/ur_mujoco/config/ur5e.yaml)l like this:

![Screenshot from 2023-08-20 10-30-30](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/a50ba2fa-6d55-4b05-b30f-7f8f3aa233a9)
![Screenshot from 2023-08-20 10-30-32](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/c298f88d-21a2-4631-bfc1-8efd35c3c230)
The robot connection runs properly,but cube connection is not established:


[Screencast from 20.08.2023 10:31:47.webm](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/7372165a-43be-4149-971d-4db4509f172b)
Your guidance on setting up the cube connection would be greatly appreciated.
Thank you again for your detailed video!

**Comment by HoangGiang93** [comment]
It couldn't move because of probably 2 reasons:
1) You set the constraint to ball. When you have a constraint, you can't freely move the object as you want in Unreal. Try to change to freejoint instead.
2) The joint and body name are the same. It could cause problem, try to change the joint name and see if it works.

About the installation, can you run `sudo ./install.sh` and `./build_third_parties.sh` again? I guess you didn't do `./build_third_parties.sh`

**Comment by HoangGiang93** [comment]
And another thing, you should modify the yaml file like this:
```
send:
    ur5e: [position, quaternion]
    joint: [joint_rvalue, joint_tvalue]

  receive:
    StaticMeshActor_1: [position, quaternion]
```

As before, if you include `body: [position, quaternion]` in `send`, it will consider all objects from MuJoCo is to be sent.

**Comment by Nash-dc** [comment]
Thanks for your reply!
Actually I follow this instruction to build the Multiverse:
```
sudo ./install.sh      # Install all prerequisites
./build_third_parties.sh        # Build the dependencies
./build_multiverse.sh           # Build the software
./build_multiverse_ws.sh        # Build the ROS workspace
```
I just delete the Multiverse and build it again,the same problem still remains.
I modified  the yaml file like this as you said
![Screenshot from 2023-08-20 12-24-42](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/1aebbdca-efb0-4117-9cf9-f61ef32f43a7)
then I run `roslaunch ur_mujoco mujoco.launch`
then I get the following errors:
```
dacheng@MyWondefulComputer:~$ roslaunch ur_mujoco mujoco.launch
... logging to /home/dacheng/.ros/log/6801fcae-3f43-11ee-a83c-4353074b01cf/roslaunch-MyWondefulComputer-11774.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: error loading <rosparam> tag: 
	file /home/dacheng/Documents/Multiverse/multiverse_ws/src/Multiverse-Robots/universal_robots/ur_mujoco/config/ur5e.yaml contains invalid YAML:
while parsing a block mapping
  in "<unicode string>", line 15, column 3:
      send:
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 19, column 5:
        receive:
        ^
XML is <rosparam command="load" file="$(arg config)"/>
The traceback for the exception was written to the log file
```
It seems like this is not a correct form, so I modify like this:
![Screenshot from 2023-08-20 12-27-27](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/6ad872af-9e2f-409b-b5bb-ec749f1b486e)
I also changed it to freejoint:

![Screenshot from 2023-08-20 12-28-19](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/6be95397-9904-464b-831a-a8fbc86d1cf6)

then it look like this:
[Screencast from 20.08.2023 12:34:29.webm](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/2942c979-a941-4f1d-891b-f22bdddf3913)
By the way, if I remove the receive object in MultiverseActor and change the yaml file like this:

![Screenshot from 2023-08-20 12-36-43](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/83dceee5-411b-4fe2-aa50-dbb94423b05e)

![Screenshot from 2023-08-20 12-37-23](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/437a71f6-3bd0-4469-951e-248e902c2e97)

 then the cube connection is established:

[Screencast from 20.08.2023 12:39:01.webm](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/d163ee35-f837-4ad3-9cff-907646475f14)

**Comment by Nash-dc** [comment]
I know what cause the installation issue.The blender requires GCC 11.0.0, but I have GCC 9.4.0.I solved it by updating my GCC version, thanks a lot!

**Comment by HoangGiang93** [comment]
The yaml file should be like this:
![image](https://github.com/Multiverse-Framework/Multiverse/assets/64316740/7e48a8ef-1d00-43fe-b67c-87282e6a53ba)
Can you send the log of the installation?

**Comment by HoangGiang93** [comment]
> I know what cause the installation issue.The blender requires GCC 11.0.0, but I have GCC 9.4.0.I solved it by updating my GCC version, thanks a lot!

I'm aware of that, therefore I explicitly put GCC 11 in the install.sh and change its version. The fact that your installation still using GCC 9.4.0 confused me :/

**Comment by Nash-dc** [comment]
If I run `sudo apt-get install gcc-11` I got the following errors
```
dacheng@MyWondefulComputer:~/Documents/Multiverse$ sudo apt-get install gcc-11
[sudo] password for dacheng: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gcc-11
```
I think that is the reason why it didn't work

**Comment by Nash-dc** [comment]
It would be great if you can add this command in install.sh
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test
`
then the gcc-11 can be definitely found.

**Comment by Nash-dc** [comment]
Thank you Mr.Hoang! 
I changed the body to ur5e then the connection is established.
I truly appreciate your consistent assistance. Please feel free to reach out if there's anything I can do to assist you in return.

**Comment by HoangGiang93** [comment]
> Thank you Mr.Hoang! I changed the body to ur5e then the connection is established. I truly appreciate your consistent assistance. Please feel free to reach out if there's anything I can do to assist you in return.

I'm glad to hear that. Your interest on my framework is already a pleasure for me. And yes, I will add `add-apt-repository ppa:ubuntu-toolchain-r/test` to `install.sh`. If you found anything like that, please let me know. Creating an installation process that works globally is really not trivial at all ;__;
